# Generated by Django 4.0.10 on 2023-11-15 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_kyc_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='account',
        ),
    ]
