# Generated by Django 4.0.10 on 2023-11-27 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='desciption',
            new_name='description',
        ),
    ]
